import { invoke } from '@tauri-apps/api/core'
import type { DemoAnalysisJob, DemoListPage, DemoPlaybackResult, DemoRecordingSettings, DemoReport, DemoRoot, DemoScanResult, ExportMatchResult, HeatmapExportResult, HeatmapFilters, HeatmapPoint, MatchDuelMatrix, MatchEconomyRow, MatchEventFilters, MatchEventPage, MatchOverview, MatchRoundSummary, MatchScoreboardPlayer, MatchUtilityRow, PlayerMatchDetail, RevealDemoResult, RoundPositions } from '@/types/demo'

export const listDemoRoots = () => invoke<DemoRoot[]>('list_demo_roots')
export const playDemo = (demoId: number, rootPath: string) => invoke<DemoPlaybackResult>('play_demo', { demoId, rootPath })
export const revealDemoFile = (demoId: number) => invoke<RevealDemoResult>('reveal_demo_file', { demoId })
export const addDemoRoot = (path: string, scanDepth = 5) => invoke<DemoRoot>('add_demo_root', { path, scanDepth })
export const ensureDefaultDemoRoot = (rootPath: string) => invoke<DemoRoot>('ensure_default_demo_root', { rootPath })
export const updateDemoRoot = (id: number, enabled: boolean, scanDepth: number) => invoke<void>('update_demo_root', { id, enabled, scanDepth })
export const removeDemoRoot = (id: number) => invoke<void>('remove_demo_root', { id })
export const deleteDemoFile = (demoId: number) => invoke<void>('delete_demo_file', { demoId })
export const scanDemoRoots = (rootId?: number) => invoke<DemoScanResult>('scan_demo_roots', { rootId })
export const importDemoFile = (path: string) => invoke<{ demoFileId: number; status: string }>('import_demo_file', { path })
export const listDemos = (query: string, status: string, page: number, pageSize: number) => invoke<DemoListPage>('list_demos', { query, status, page, pageSize })
export const listAnalysisJobs = (activeOnly = false) => invoke<DemoAnalysisJob[]>('list_analysis_jobs', { activeOnly })
export const cancelAnalysisJob = (jobId: number) => invoke<void>('cancel_analysis_job', { jobId })
export const retryAnalysisJob = (jobId: number) => invoke<void>('retry_analysis_job', { jobId })
export const getMatchOverview = (demoId: number) => invoke<MatchOverview>('get_match_overview', { demoId })
export const getMatchScoreboard = (demoId: number) => invoke<MatchScoreboardPlayer[]>('get_match_scoreboard', { demoId })
export const getMatchRounds = (demoId: number) => invoke<MatchRoundSummary[]>('get_match_rounds', { demoId })
export const getMatchEconomy = (demoId: number) => invoke<MatchEconomyRow[]>('get_match_economy', { demoId })
export const getMatchDuels = (demoId: number) => invoke<MatchDuelMatrix>('get_match_duels', { demoId })
export const getMatchUtility = (demoId: number) => invoke<MatchUtilityRow[]>('get_match_utility', { demoId })
export const getMatchEvents = (demoId: number, filters: MatchEventFilters, page = 1, pageSize = 100) => invoke<MatchEventPage>('get_match_events', { demoId, filters, page, pageSize })
export const getPlayerMatchDetail = (demoId: number, stableKey: string) => invoke<PlayerMatchDetail>('get_player_match_detail', { demoId, stableKey })
export const exportMatch = (demoId: number, format: 'json' | 'csv', destinationPath: string) => invoke<ExportMatchResult>('export_match', { demoId, format, destinationPath })
export const ensureSpatialAnalysis = (demoId: number, samplingHz = 8) => invoke<number>('ensure_spatial_analysis', { demoId, samplingHz })
export const getRoundPositions = (demoId: number, roundNumber: number, samplingHz = 8) => invoke<RoundPositions>('get_round_positions', { demoId, roundNumber, samplingHz })
export const getHeatmapPoints = (demoId: number, filters: HeatmapFilters = { kind: 'player_death' }) => invoke<HeatmapPoint[]>('get_heatmap_points', { demoId, filters })
export const saveHeatmapPng = (demoId: number, filters: HeatmapFilters, destinationPath: string) => invoke<HeatmapExportResult>('save_heatmap_png', { demoId, filters, destinationPath })
export const launchDemoAtTick = (demoId: number, tick: number, playerKey?: string) => invoke<{ demoFileId: number; tick: number; path: string }>('launch_demo_at_tick', { demoId, tick, playerKey })
export const getDemoReport = (id: number) => invoke<DemoReport>('get_demo_report', { id })
export const retryDemoParse = (id: number) => invoke<{ demoFileId: number; status: string }>('retry_demo_parse', { id })
export const getDemoSettings = (rootPath: string) => invoke<DemoRecordingSettings>('get_demo_settings', { rootPath })
export const setDemoRecordingEnabled = (rootPath: string, enabled: boolean) => invoke<DemoRecordingSettings>('set_demo_recording_enabled', { rootPath, enabled })
