<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { FilePlus2, FolderPlus, RefreshCw, RotateCcw, Trash2 } from 'lucide-vue-next'
import { useDemoStore } from '@/stores/demo'

const demo = useDemoStore(); const tab = ref<'library' | 'report'>('library')
const pages = computed(() => Math.max(1, Math.ceil(demo.total / demo.pageSize)))
const scoreboardGroups = computed(() => {
  if (!demo.report) return []
  return [
    { key: 't', label: 'T 阵营', players: demo.report.players.filter(player => player.teamNumber === 2 || player.team === 'T') },
    { key: 'ct', label: 'CT 阵营', players: demo.report.players.filter(player => player.teamNumber === 3 || player.team === 'CT') },
    { key: 'unknown', label: '未识别队伍', players: demo.report.players.filter(player => ![2, 3].includes(player.teamNumber ?? -1) && !['T', 'CT'].includes(player.team ?? '')) },
  ].filter(group => group.players.length)
})
const statusLabel: Record<string, string> = { parsing: '解析中', done: '已完成', error: '解析失败' }
const eventLabel: Record<string, string> = { player_death: '击杀', bomb_beginplant: '开始下包', bomb_planted: '已下包', bomb_begindefuse: '开始拆包', bomb_defused: '已拆包', bomb_exploded: '炸弹爆炸' }
const fmtDate = (value: number | null) => value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '--'
const fmtSize = (value: number) => `${(value / 1024 / 1024).toFixed(1)} MB`
async function chooseRoot() { const { open } = await import('@tauri-apps/plugin-dialog'); const path = await open({ directory: true, multiple: false, title: '添加 Demo 目录' }); if (typeof path === 'string') await demo.addRoot(path) }
async function chooseFile() { const { open } = await import('@tauri-apps/plugin-dialog'); const path = await open({ directory: false, multiple: false, filters: [{ name: 'CS2 Demo', extensions: ['dem'] }], title: '导入 Demo' }); if (typeof path === 'string') { await demo.importFile(path); if (demo.report) tab.value = 'report' } }
async function openReport(id: number) { await demo.openReport(id); if (demo.report) tab.value = 'report' }
let filterTimer: ReturnType<typeof setTimeout> | undefined
watch([() => demo.query, () => demo.status, () => demo.pageSize], () => { demo.page = 1; clearTimeout(filterTimer); filterTimer = setTimeout(() => demo.refresh(), 180) })
watch(() => demo.page, () => demo.refresh())
onMounted(() => demo.refresh())
</script>

<template>
  <section class="tool-view demo-review" aria-labelledby="demo-title">
    <header class="view-heading demo-heading"><div><p class="overline">本地数据</p><h1 id="demo-title">对局复盘</h1></div><div class="demo-actions"><button class="secondary-button" type="button" @click="chooseRoot"><FolderPlus :size="18" />添加目录</button><button class="secondary-button" type="button" @click="chooseFile"><FilePlus2 :size="18" />导入 Demo</button><button class="primary-button" type="button" :disabled="demo.busy === 'scan' || !demo.roots.length" @click="demo.scan"><RefreshCw :size="18" :class="{ spinning: demo.busy === 'scan' }" />{{ demo.busy === 'scan' ? '正在扫描' : '立即扫描' }}</button></div></header>
    <div class="demo-tabs" role="tablist" aria-label="对局复盘视图"><button type="button" role="tab" :aria-selected="tab === 'library'" @click="tab = 'library'">录像库</button><button type="button" role="tab" :aria-selected="tab === 'report'" :disabled="!demo.report" @click="tab = 'report'">对局报告</button></div>
    <p v-if="demo.error" class="inline-error" role="alert">{{ demo.error }}</p>
    <template v-if="tab === 'library'">
      <section class="demo-roots" aria-labelledby="roots-title"><div class="section-heading"><div><h2 id="roots-title">扫描目录</h2><p>已选择的 CS2 根目录会自动加入，默认深度 5。</p></div></div><div v-if="demo.roots.length" class="root-list"><div v-for="root in demo.roots" :key="root.id" class="root-row"><label><input type="checkbox" :checked="root.enabled" @change="demo.updateRoot(root, ($event.target as HTMLInputElement).checked)" /><span class="root-path" :title="root.path">{{ root.path }}</span><small v-if="root.origin === 'selected_cs2_root'">自动</small></label><select :value="root.scanDepth" aria-label="扫描深度" @change="demo.updateRoot(root, root.enabled, Number(($event.target as HTMLSelectElement).value))"><option v-for="depth in [0,1,2,3,5]" :key="depth" :value="depth">深度 {{ depth }}</option></select><span>{{ fmtDate(root.lastScanAt) }}</span><button class="icon-button" type="button" title="移除目录" aria-label="移除目录" @click="demo.removeRoot(root.id)"><Trash2 :size="17" /></button></div></div><div v-else class="demo-empty"><strong>尚未添加 Demo 目录</strong><span>添加 CS2 replays 目录，或直接导入一个 .dem 文件。</span><button class="secondary-button" type="button" @click="chooseRoot"><FolderPlus :size="18" />添加目录</button></div></section>
      <div class="demo-filters"><label><span class="sr-only">搜索录像</span><input v-model="demo.query" type="search" placeholder="搜索文件名或地图" /></label><select v-model="demo.status" aria-label="解析状态"><option value="all">全部状态</option><option value="done">已完成</option><option value="parsing">解析中</option><option value="error">解析失败</option></select><select v-model.number="demo.pageSize" aria-label="每页数量"><option :value="25">25 / 页</option><option :value="50">50 / 页</option><option :value="100">100 / 页</option></select></div>
      <div class="demo-table-wrap"><table class="demo-table"><thead><tr><th>文件名</th><th>地图</th><th>回合</th><th>击杀</th><th>文件时间</th><th>大小</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in demo.items" :key="item.id" @dblclick="item.status === 'done' && openReport(item.id)"><td><strong :title="item.path">{{ item.fileName }}</strong></td><td>{{ item.mapName || '--' }}</td><td>{{ item.totalRounds ?? '--' }}</td><td>{{ item.kills ?? '--' }}</td><td>{{ fmtDate(item.mtimeMs) }}</td><td>{{ fmtSize(item.sizeBytes) }}</td><td><span class="demo-status" :data-status="item.status">{{ statusLabel[item.status] || item.status }}</span></td><td><button v-if="item.status === 'done'" class="text-button" type="button" @click="openReport(item.id)">打开报告</button><button v-else-if="item.status === 'error'" class="icon-button" type="button" title="重新解析" aria-label="重新解析" @click="demo.retry(item.id)"><RotateCcw :size="16" /></button></td></tr><tr v-if="!demo.items.length"><td colspan="8"><div class="demo-empty"><strong>{{ demo.busy === 'list' ? '正在读取录像库' : '没有符合条件的 Demo' }}</strong><span>导入文件或扫描已添加目录。</span></div></td></tr></tbody></table></div>
      <footer class="demo-pagination"><span>共 {{ demo.total }} 个 Demo</span><button type="button" :disabled="demo.page <= 1" @click="demo.page--">上一页</button><span>{{ demo.page }} / {{ pages }}</span><button type="button" :disabled="demo.page >= pages" @click="demo.page++">下一页</button></footer>
    </template>
    <template v-else-if="demo.report">
      <section class="report-summary"><div><p class="overline">比赛摘要</p><h2>{{ demo.report.summary.mapName || '未知地图' }}</h2><p :title="demo.report.summary.path">{{ demo.report.summary.fileName }}</p></div><dl><div><dt>回合</dt><dd>{{ demo.report.summary.totalRounds || '--' }}</dd></div><div><dt>击杀事件</dt><dd>{{ demo.report.summary.totalKills }}</dd></div><div><dt>文件时间</dt><dd>{{ fmtDate(demo.report.summary.fileTimeMs) }}</dd></div><div><dt>解析器</dt><dd>{{ demo.report.parserName }}</dd></div></dl></section>
      <section class="report-section"><div class="section-heading scoreboard-heading"><div><h2>记分板</h2><p>{{ demo.report.dataQuality.scoreboardStatus === 'complete' ? '终局身份与统计已完整解析。' : demo.report.dataQuality.scoreboardStatus === 'partial' ? '已启用兼容恢复，缺失字段保持为 --。' : '当前报告没有可用的玩家身份。' }}</p></div><button v-if="demo.report.dataQuality.scoreboardStatus !== 'complete'" class="secondary-button" type="button" :disabled="demo.busy === `retry-${demo.report.summary.demoFileId}`" @click="demo.retry(demo.report.summary.demoFileId)"><RotateCcw :size="16" />重新解析</button></div><div v-if="demo.report.dataQuality.warnings.length" class="scoreboard-warning" role="status" aria-live="polite"><p v-for="warning in demo.report.dataQuality.warnings" :key="warning">{{ warning }}</p></div><div class="demo-table-wrap"><table class="demo-table scoreboard"><thead><tr><th>玩家</th><th>SteamID</th><th>队伍</th><th>K</th><th>D</th><th>A</th><th>伤害</th><th>爆头</th></tr></thead><tbody><template v-for="group in scoreboardGroups" :key="group.key"><tr class="scoreboard-group" :data-team="group.key"><th colspan="8">{{ group.label }} · {{ group.players.length }} 人</th></tr><tr v-for="player in group.players" :key="player.key"><td :title="player.name || undefined">{{ player.name || '--' }}</td><td>{{ player.isBot ? 'BOT' : player.steamId || '--' }}</td><td>{{ player.team || '--' }}</td><td>{{ player.kills ?? '--' }}</td><td>{{ player.deaths ?? '--' }}</td><td>{{ player.assists ?? '--' }}</td><td>{{ player.damage ?? '--' }}</td><td>{{ player.headshots ?? '--' }}</td></tr></template><tr v-if="!demo.report.players.length"><td colspan="8">{{ demo.report.schemaVersion < 2 ? '报告由旧解析器生成，需要重新解析。' : demo.report.dataQuality.warnings[0] || '解析器未能恢复玩家身份。' }}</td></tr></tbody></table></div></section>
      <section class="report-section"><div class="section-heading"><div><h2>回合时间线</h2><p>击杀与炸弹事件按已解析的回合边界归组。</p></div></div><div class="round-list"><details v-for="round in demo.report.rounds" :key="round.number" :open="round.number === 1"><summary><strong>第 {{ round.number }} 回合</strong><span>Tick {{ round.startTick ?? '--' }} - {{ round.endTick ?? '--' }}</span><span>{{ round.kills.length }} 击杀 · {{ round.bombEvents.length }} 炸弹事件</span></summary><div class="event-list"><div v-for="event in [...round.kills, ...round.bombEvents].sort((a,b) => a.tick-b.tick)" :key="`${event.tick}-${event.kind}`"><time>Tick {{ event.tick }}</time><strong>{{ eventLabel[event.kind] || event.kind }}</strong><span>{{ event.actor || '--' }}<template v-if="event.target"> → {{ event.target }}</template><template v-if="event.weapon"> · {{ event.weapon }}</template><template v-if="event.headshot"> · 爆头</template></span></div><p v-if="!round.kills.length && !round.bombEvents.length">本回合没有已解析的关键事件。</p></div></details></div></section>
    </template>
  </section>
</template>
