export interface DemoRoot { id: number; path: string; enabled: boolean; scanDepth: number; lastScanAt: number | null; lastError: string | null; origin: string }
export interface DemoScanResult { rootPaths: string[]; scannedDirectories: number; discoveredDemFiles: number; imported: number; cacheHits: number; parsed: number; failed: number; permissionErrors: number; lastScanAt: number }
export interface DemoListItem { id: number; fileName: string; path: string; sizeBytes: number; mtimeMs: number; status: 'queued' | 'parsing' | 'done' | 'error'; errorCode: string | null; mapName: string | null; totalRounds: number | null; kills: number | null; parsedAt: number | null }
export interface DemoListPage { items: DemoListItem[]; total: number; page: number; pageSize: number }
export interface DemoPlaybackResult { demoFileId: number; sessionId: string; sourcePath: string; preparedPath: string; started: boolean }
export interface RevealDemoResult { demoFileId: number; path: string; revealed: boolean }
export interface PostMatchReportReady { sessionId: string; reportId: number; fileName: string; completedAt: number; origin: 'post_match' }
export interface PostMatchReportFailed { sessionId: string; demoId: number | null; errorCode: string; message: string }
export interface DemoAnalysisJob { id: number; demoFileId: number; fileName: string; kind: 'core' | 'spatial'; stage: string; progress: number; attempts: number; errorCode: string | null; errorDetail: string | null; createdAt: number; startedAt: number | null; finishedAt: number | null }
export interface MatchOverview { demoFileId: number; fileName: string; mapName: string | null; serverName: string | null; teamAScore: number | null; teamBScore: number | null; totalRounds: number; totalKills: number; analyzedAt: number | null; qualityJson: string | null }
export interface MatchScoreboardPlayer { stableKey: string; name: string | null; steamId: string | null; isBot: boolean; teamName: string | null; teamNumber: number | null; kills: number | null; deaths: number | null; assists: number | null; damageHealth: number | null; headshots: number | null; adr: number | null; kastPercent: number | null; rating: number | null; ratingModel: string | null }
export interface MatchRoundSummary { roundNumber: number; startTick: number | null; freezeEndTick: number | null; endTick: number | null; officialEndTick: number | null; winnerSide: string | null; reason: string | null; eventCount: number }
export interface DemoEvent { tick: number; kind: string; actor: string | null; target: string | null; actorKey: string | null; targetKey: string | null; weapon: string | null; headshot: boolean | null; detail: string | null; payload: unknown }
export interface DemoRound { number: number; startTick: number | null; endTick: number | null; winner: string | null; reason: string | null; kills: DemoEvent[]; bombEvents: DemoEvent[]; events: DemoEvent[] }
export type PlayerRatingStatus = 'complete' | 'unavailable'
export type ReportRatingStatus = 'complete' | 'partial' | 'unavailable'
export interface DemoRating { modelVersion: string; killComponent: number; damageComponent: number; survivalComponent: number; assistComponent: number; rating: number }
export interface DemoPlayer { key: string; steamId: string | null; userId: number | null; name: string | null; isBot: boolean; participantRole: 'player' | 'observer' | 'unknown'; teamNumber: number | null; team: string | null; kills: number | null; deaths: number | null; assists: number | null; damage: number | null; headshots: number | null; identitySource: string; statsSource: string; roundsPlayed: number | null; roundsSurvived: number | null; kastRounds: number | null; multiKills: number | null; firstKills: number | null; firstDeaths: number | null; tradeKills: number | null; tradeDenials: number | null; adr: number | null; kastPercent: number | null; headshotPercent: number | null; roundSwing: number | null; economyAdjustment: number | null; ratingStatus: PlayerRatingStatus; rating: DemoRating | null }
export interface DemoDataQuality { scoreboardStatus: 'complete' | 'partial' | 'unavailable'; warnings: string[]; entityParseStatus: 'strict' | 'recovered' | 'failed'; ratingStatus: ReportRatingStatus; ratingWarnings: string[]; scoreSource: string; scoreQuality: 'complete' | 'partial' | 'unavailable' | 'conflict'; scoreWarnings: string[]; canonicalCtScore: number | null; canonicalTScore: number | null; propsCtScore: number | null; propsTScore: number | null; logicalRounds: number; completedRounds: number; unfinishedRounds: number }
export interface DemoReport { schemaVersion: number; parserName: string; parserCommit: string; parserAdapterVersion: string; metricsVersion: string; appVersion: string; dataQuality: DemoDataQuality; summary: { demoFileId: number; fileName: string; path: string; mapName: string | null; serverName: string | null; fileTimeMs: number; sizeBytes: number; totalRounds: number; totalKills: number; teamAScore: number | null; teamBScore: number | null; parsedAt: number }; players: DemoPlayer[]; rounds: DemoRound[] }
export interface DemoRecordingSettings { desiredEnabled: boolean; normalCfgApplied: boolean; ffaCfgApplied: boolean; drifted: boolean; writable: boolean; scope: 'bots-only' }
export interface MatchEconomyRow { roundNumber: number; teamNumber: number; team: string | null; equipmentValue: number | null; moneyStart: number | null; moneySpent: number | null; economyType: string | null; quality: string | null }
export interface MatchDuelPlayer { key: string; name: string | null; isBot: boolean }
export interface MatchDuelTeam { number: number | null; label: string; players: MatchDuelPlayer[] }
export interface MatchDuelCell { xPlayerKey: string; yPlayerKey: string; xKillsY: number; yKillsX: number }
export interface MatchDuelMatrix { teamX: MatchDuelTeam; teamY: MatchDuelTeam; cells: MatchDuelCell[] }
export interface MatchUtilityRow { stableKey: string; playerName: string | null; heDamage: number | null; flashVictims: number; throws: number }
export interface MatchEventFilters { kind?: string | null; roundNumber?: number | null; playerKey?: string | null }
export interface MatchEventRow { id: number; roundNumber: number | null; tick: number; kind: string; actorKey: string | null; targetKey: string | null; payloadJson: string; quality: string | null }
export interface MatchEventPage { items: MatchEventRow[]; total: number; page: number; pageSize: number }
export interface PlayerRoundDetail { roundNumber: number; side: string | null; kills: number | null; deaths: number | null; assists: number | null; damageHealth: number | null; survived: boolean | null; traded: boolean | null; kast: boolean | null }
export interface PlayerMatchDetail { player: MatchScoreboardPlayer; rounds: PlayerRoundDetail[] }
export interface ExportMatchResult { path: string; bytesWritten: number }
export type HeatmapLayer = 'upper' | 'lower' | 'all'
export interface HeatmapFilters { kind: string; roundNumbers?: number[]; playerKeys?: string[]; teamNumbers?: Array<2 | 3>; layer?: HeatmapLayer; radius?: number; opacity?: number }
export interface HeatmapExportResult { path: string; bytesWritten: number; width: number; height: number; mapName: string; layer: HeatmapLayer; inputPoints: number; renderedPoints: number; discardedPoints: number; assetSha256: string; outputSha256: string }
export interface PositionPoint { tick: number; stableKey: string; name: string | null; x: number; y: number; z: number; yaw: number | null; health: number | null; armor: number | null; teamNumber: number | null; participantRole?: 'player' | 'observer' | 'unknown'; alive: boolean | null; weapon: string | null }
export interface RoundPositions { demoFileId: number; roundNumber: number; samplingHz: number; points: PositionPoint[] }
export interface HeatmapPoint { tick: number; x: number; y: number; z: number | null; weight: number; kind: string; roundNumber: number | null; playerKey: string | null; teamNumber: number | null }
