export interface DemoRoot { id: number; path: string; enabled: boolean; scanDepth: number; lastScanAt: number | null; lastError: string | null; origin: string }
export interface DemoScanResult { rootPaths: string[]; scannedDirectories: number; discoveredDemFiles: number; imported: number; cacheHits: number; parsed: number; failed: number; permissionErrors: number; lastScanAt: number }
export interface DemoListItem { id: number; fileName: string; path: string; sizeBytes: number; mtimeMs: number; status: 'parsing' | 'done' | 'error'; errorCode: string | null; mapName: string | null; totalRounds: number | null; kills: number | null; parsedAt: number | null }
export interface DemoListPage { items: DemoListItem[]; total: number; page: number; pageSize: number }
export interface DemoEvent { tick: number; kind: string; actor: string | null; target: string | null; weapon: string | null; headshot: boolean | null; detail: string | null }
export interface DemoRound { number: number; startTick: number | null; endTick: number | null; winner: string | null; reason: string | null; kills: DemoEvent[]; bombEvents: DemoEvent[] }
export type PlayerRatingStatus = 'complete' | 'unavailable'
export type ReportRatingStatus = 'complete' | 'partial' | 'unavailable'
export interface DemoRating { modelVersion: string; killComponent: number; damageComponent: number; survivalComponent: number; assistComponent: number; rating: number }
export interface DemoPlayer { key: string; steamId: string | null; userId: number | null; name: string | null; isBot: boolean; teamNumber: number | null; team: string | null; kills: number | null; deaths: number | null; assists: number | null; damage: number | null; headshots: number | null; identitySource: string; statsSource: string; roundsPlayed: number | null; roundsSurvived: number | null; kastRounds: number | null; multiKills: number | null; firstKills: number | null; firstDeaths: number | null; tradeKills: number | null; tradeDenials: number | null; adr: number | null; kastPercent: number | null; headshotPercent: number | null; roundSwing: number | null; economyAdjustment: number | null; ratingStatus: PlayerRatingStatus; rating: DemoRating | null }
export interface DemoDataQuality { scoreboardStatus: 'complete' | 'partial' | 'unavailable'; warnings: string[]; entityParseStatus: 'strict' | 'recovered' | 'failed'; ratingStatus: ReportRatingStatus; ratingWarnings: string[] }
export interface DemoReport { schemaVersion: number; parserName: string; parserCommit: string; parserAdapterVersion: string; metricsVersion: string; appVersion: string; dataQuality: DemoDataQuality; summary: { demoFileId: number; fileName: string; path: string; mapName: string | null; serverName: string | null; fileTimeMs: number; sizeBytes: number; totalRounds: number; totalKills: number; teamAScore: number | null; teamBScore: number | null; parsedAt: number }; players: DemoPlayer[]; rounds: DemoRound[] }
export interface DemoRecordingSettings { desiredEnabled: boolean; normalCfgApplied: boolean; ffaCfgApplied: boolean; drifted: boolean; writable: boolean; scope: 'bots-only' }
