import type { ThreeStageController, StageSize } from '@/components/three/stage'
import type { IntroAcknowledgementCard } from './types'
import { buildPlaqueLayout, type PlaqueLayoutSlot } from '@/features/acknowledgement/layout'

export interface IntroSceneState { elapsedMs: number; durationMs: number; supporterLockMs: number; loading: boolean; cards: IntroAcknowledgementCard[]; mode?: 'cinematic' | 'free-roam'; selectedIndex?: number }
export function introCardSignature(cards: IntroAcknowledgementCard[]) { return cards.map(item => `${item.id}:${item.updatedAt}`).join('|') }
const clamp = (n: number, min: number, max: number) => Math.max(min, Math.min(max, n))
const ease = (t: number) => { const x = clamp(t, 0, 1); return x < .5 ? 4 * x ** 3 : 1 - (-2 * x + 2) ** 3 / 2 }
function fit(ctx: CanvasRenderingContext2D, value: string, width: number) { let s = value || '无名同路人'; while (s.length > 1 && ctx.measureText(`${s}…`).width > width) s = s.slice(0, -1); return s === value ? s : `${s}…` }

/** Shared ink-wash corridor. Plaques follow a growing timeline, never stacking in depth. */
export async function createIntroScene(canvas: HTMLCanvasElement, size: StageSize, getState: () => IntroSceneState): Promise<ThreeStageController> {
  const THREE = await import('three')
  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' }); renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.setClearColor(0xf2ebdf, 1)
  const scene = new THREE.Scene(); scene.background = new THREE.Color(0xf2ebdf); scene.fog = new THREE.Fog(0xf2ebdf, 18, 72); const camera = new THREE.PerspectiveCamera(42, 1, .1, 120); const target = new THREE.Vector3()
  const groups: Array<{ group: InstanceType<typeof THREE.Group>; slot: PlaqueLayoutSlot; texture: InstanceType<typeof THREE.CanvasTexture>; light: InstanceType<typeof THREE.PointLight> }> = []; const geometries = new Set<InstanceType<typeof THREE.BufferGeometry>>(); const materials = new Set<InstanceType<typeof THREE.Material>>(); const textures = new Set<InstanceType<typeof THREE.Texture>>()
  const geo = <T extends InstanceType<typeof THREE.BufferGeometry>>(v: T) => (geometries.add(v), v); const mat = <T extends InstanceType<typeof THREE.Material>>(v: T) => (materials.add(v), v)
  scene.add(new THREE.HemisphereLight(0xfffaf2, 0x8d867c, 2.2)); const sun = new THREE.DirectionalLight(0xfff8e9, 2.6); sun.position.set(-8, 14, 10); scene.add(sun)
  const ink = mat(new THREE.MeshStandardMaterial({ color: 0x262624, roughness: .92 })); const paper = mat(new THREE.MeshStandardMaterial({ color: 0xd9d0c2, roughness: 1 })); const floor = new THREE.Mesh(geo(new THREE.PlaneGeometry(140, 38)), mat(new THREE.MeshStandardMaterial({ color: 0xe9e0d3, roughness: 1 }))); floor.rotation.x = -Math.PI / 2; floor.position.y = -.05; scene.add(floor)
  const path = new THREE.Mesh(geo(new THREE.PlaneGeometry(140, .035)), ink); path.rotation.x = -Math.PI / 2; path.position.y = .012; scene.add(path)
  const hill = new THREE.Mesh(geo(new THREE.PlaneGeometry(46, 8)), mat(new THREE.MeshBasicMaterial({ color: 0xc7bcae, transparent: true, opacity: .42 }))); hill.position.set(4, 3, -14); scene.add(hill)
  const base = geo(new THREE.CylinderGeometry(1.1, 1.28, .42, 12)); const plaque = geo(new THREE.BoxGeometry(3.9, 2.35, .12)); const face = geo(new THREE.PlaneGeometry(3.7, 2.15))
  function textureFor(card: IntroAcknowledgementCard) { const c = document.createElement('canvas'); c.width = 740; c.height = 430; const x = c.getContext('2d'); if (!x) throw new Error('无法创建牌面'); x.fillStyle = '#262624'; x.fillRect(0, 0, c.width, c.height); x.strokeStyle = card.kind === 'upstream' ? '#d1aa67' : '#e8d7bd'; x.lineWidth = 5; x.strokeRect(17, 17, c.width - 34, c.height - 34); x.fillStyle = '#e8dfd2'; x.font = '600 25px "Microsoft YaHei UI", sans-serif'; x.fillText(fit(x, card.eyebrow, 630), 48, 70); x.fillStyle = '#fffaf2'; x.font = '700 42px "Microsoft YaHei UI", sans-serif'; x.fillText(fit(x, card.title, 630), 48, 150); x.fillStyle = '#c9c1b6'; x.font = '400 23px "Microsoft YaHei UI", sans-serif'; x.fillText(fit(x, card.message, 630), 48, 225); x.fillStyle = '#d1aa67'; x.font = '600 24px "Microsoft YaHei UI", sans-serif'; x.fillText(fit(x, card.detail, 630), 48, 338); return c }
  function clear() { groups.splice(0).forEach(item => { scene.remove(item.group); item.texture.dispose() }) }
  let signature = ''
  function rebuild(cards: IntroAcknowledgementCard[]) { clear(); const list = cards.length ? cards : [{ id: 'fallback', kind: 'supporter' as const, eyebrow: '鸣谢长廊', title: '致每一位同路人', message: '感谢你的支持与同行。', detail: 'CS2AS', updatedAt: '' }]; const slots = buildPlaqueLayout(list); list.forEach((card, index) => { const slot = slots[index] ?? { id: card.id, x: index * 4.6, z: 0, rotationY: 0, order: index }; const g = new THREE.Group(); g.position.set(slot.x, .25, slot.z); g.rotation.y = slot.rotationY; const b = new THREE.Mesh(base, paper); b.position.y = .2; const p = new THREE.Mesh(plaque, ink); p.position.y = 2.05; const t = new THREE.CanvasTexture(textureFor(card)); t.colorSpace = THREE.SRGBColorSpace; textures.add(t); const m = mat(new THREE.MeshBasicMaterial({ map: t })); const f = new THREE.Mesh(face, m); f.position.set(0, 2.05, .075); const r = new THREE.Mesh(face, m); r.position.set(0, 2.05, -.075); r.rotation.y = Math.PI; const l = new THREE.PointLight(card.kind === 'upstream' ? 0xc9a15e : 0x8f8a80, 3.2, 7); l.position.set(0, 2.5, 1.1); g.add(b, p, f, r, l); scene.add(g); groups.push({ group: g, slot, texture: t, light: l }) }) }
  function cameraAt(state: IntroSceneState) { const count = Math.max(1, groups.length); if (state.mode === 'free-roam') { const item = groups[clamp(state.selectedIndex ?? 0, 0, count - 1)]; const x = item?.slot.x ?? 0; const z = item?.slot.z ?? 0; camera.position.set(x + 7.8, 3.8, z + 8.8); target.set(x, 1.8, z); return } const t = ease(state.elapsedMs / Math.max(1, state.durationMs)); const travel = Math.min(count - 1, t * count); const left = Math.floor(travel); const right = Math.min(count - 1, left + 1); const blend = travel - left; const a = groups[left]?.slot; const b = groups[right]?.slot ?? a; const x = (a?.x ?? 0) + ((b?.x ?? 0) - (a?.x ?? 0)) * blend; const z = (a?.z ?? 0) + ((b?.z ?? 0) - (a?.z ?? 0)) * blend; camera.position.set(x - 7.4, 3.3 + Math.sin(t * Math.PI) * .4, z + 8.6); target.set(x, 1.8, z) }
  function resize(next: StageSize) { renderer.setPixelRatio(Math.min(next.dpr, 1.5)); renderer.setSize(next.width, next.height, false); camera.aspect = next.width / next.height; camera.updateProjectionMatrix() }
  resize(size); rebuild(getState().cards); cameraAt(getState()); camera.lookAt(target); renderer.render(scene, camera)
  return { resize, frame(time) { const state = getState(); const next = introCardSignature(state.cards); if (next !== signature || !groups.length) { signature = next; rebuild(state.cards) } cameraAt(state); camera.lookAt(target); groups.forEach((item, i) => { item.group.position.y = .25 + Math.sin(time * .45 + i) * .018; item.light.intensity = 3.1 + Math.sin(time * .8 + i) * .2 }); renderer.render(scene, camera) }, setLowPerformance(enabled) { renderer.setPixelRatio(1); if (enabled) sun.intensity = 1.8 }, dispose() { clear(); geometries.forEach(g => g.dispose()); materials.forEach(m => m.dispose()); textures.forEach(t => t.dispose()); renderer.dispose(); renderer.forceContextLoss() } }
}
